[package]
name = "migrations"
version = "0.1.0"
edition.workspace = true
publish = false

[lib]
name = "migrations"
path = "src/lib.rs"

[dependencies]
tokio.workspace = true
sea-orm-migration.workspace = true
