//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.14

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "analytics_client_daily")]
pub struct Model {
	#[sea_orm(primary_key, auto_increment = false)]
	pub day: Date,
	#[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
	pub client_version: String,
	#[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
	pub minecraft_version: String,
	#[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
	pub loader: String,
	#[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
	pub os: String,
	pub active_players: i32,
	pub computed_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
