//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.14

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "analytics_cosmetic_daily")]
pub struct Model {
	#[sea_orm(primary_key, auto_increment = false)]
	pub day: Date,
	#[sea_orm(primary_key, auto_increment = false)]
	pub cosmetic_id: i32,
	pub views: i64,
	pub acquisitions: i32,
	pub acquisitions_paid: i32,
	pub acquisitions_free: i32,
	pub acquisitions_granted: i32,
	pub computed_at: DateTimeWithTimeZone,
	pub revenue_minor: i64,
	pub refunded: i32,
	pub charged_back: i32,
	pub refunded_minor: i64,
	pub charged_back_minor: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
