//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.14

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "analytics_cohort_retention")]
pub struct Model {
	#[sea_orm(primary_key, auto_increment = false)]
	pub cohort_day: Date,
	#[sea_orm(primary_key, auto_increment = false)]
	pub day_offset: i32,
	pub cohort_size: i32,
	pub retained: i32,
	pub computed_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
