//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.14

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "analytics_hourly")]
pub struct Model {
	#[sea_orm(primary_key, auto_increment = false)]
	pub hour_start: DateTimeWithTimeZone,
	pub dow: i16,
	pub hour_of_day: i16,
	pub playtime_seconds: i64,
	pub active_players: i32,
	pub sessions_started: i32,
	pub peak_concurrent: i32,
	pub computed_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
