//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.14

use super::sea_orm_active_enums::BodySlot;
use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "analytics_slot_snapshot")]
pub struct Model {
	#[sea_orm(primary_key, auto_increment = false)]
	pub week_start: Date,
	#[sea_orm(primary_key, auto_increment = false)]
	pub slot: BodySlot,
	pub equipped_players: i32,
	pub computed_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
