//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.14

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "analytics_daily")]
pub struct Model {
	#[sea_orm(primary_key, auto_increment = false)]
	pub day: Date,
	pub computed_at: DateTimeWithTimeZone,
	pub dau: i32,
	pub wau: i32,
	pub mau: i32,
	pub new_users: i32,
	pub returning_users: i32,
	pub total_users: i32,
	pub playtime_seconds: i64,
	pub sessions: i32,
	pub cosmetics_acquired: i32,
	pub cosmetics_acquired_paid: i32,
	pub cosmetics_acquired_granted: i32,
	pub transactions_completed: i32,
	pub transactions_refunded: i32,
	pub gift_transactions: i32,
	pub friend_requests_sent: i32,
	pub friend_requests_accepted: i32,
	pub friendships_created: i32,
	pub blocks_created: i32,
	pub messages_sent: i32,
	pub game_sessions_created: i32,
	pub session_invites_sent: i32,
	pub session_invites_accepted: i32,
	pub tracked_link_hits: i32,
	pub gross_revenue_minor: i64,
	pub refund_amount_minor: i64,
	pub discount_amount_minor: i64,
	pub paying_users: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
