//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.12

use super::sea_orm_active_enums::AssetKind;
use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "asset")]
pub struct Model {
	#[sea_orm(primary_key)]
	pub id: i32,
	#[sea_orm(unique)]
	pub storage_path: Option<String>,
	pub url: Option<String>,
	pub asset_kind: AssetKind,
	pub content_type: Option<String>,
	pub hash: Option<String>,
	pub created_at: DateTimeWithTimeZone,
	pub updated_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
	#[sea_orm(has_many = "super::cosmetic::Entity")]
	Cosmetic,
	#[sea_orm(has_many = "super::emote::Entity")]
	Emote,
}

impl Related<super::cosmetic::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::Cosmetic.def()
	}
}

impl Related<super::emote::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::Emote.def()
	}
}

impl ActiveModelBehavior for ActiveModel {}
