//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.14

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "discount_target")]
pub struct Model {
	#[sea_orm(primary_key)]
	pub id: i32,
	pub discount_id: i32,
	pub collection_id: Option<i32>,
	pub tag_id: Option<i32>,
	pub cosmetic_id: Option<i32>,
	pub cosmetic_group_id: Option<i32>,
	pub bundle_id: Option<i32>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
	#[sea_orm(
		belongs_to = "super::bundles::Entity",
		from = "Column::BundleId",
		to = "super::bundles::Column::Id",
		on_update = "NoAction",
		on_delete = "Cascade"
	)]
	Bundles,
	#[sea_orm(
		belongs_to = "super::collections::Entity",
		from = "Column::CollectionId",
		to = "super::collections::Column::Id",
		on_update = "NoAction",
		on_delete = "Cascade"
	)]
	Collections,
	#[sea_orm(
		belongs_to = "super::cosmetic::Entity",
		from = "Column::CosmeticId",
		to = "super::cosmetic::Column::Id",
		on_update = "NoAction",
		on_delete = "Cascade"
	)]
	Cosmetic,
	#[sea_orm(
		belongs_to = "super::cosmetic_group::Entity",
		from = "Column::CosmeticGroupId",
		to = "super::cosmetic_group::Column::Id",
		on_update = "NoAction",
		on_delete = "Cascade"
	)]
	CosmeticGroup,
	#[sea_orm(
		belongs_to = "super::discount::Entity",
		from = "Column::DiscountId",
		to = "super::discount::Column::Id",
		on_update = "NoAction",
		on_delete = "Cascade"
	)]
	Discount,
	#[sea_orm(
		belongs_to = "super::tags::Entity",
		from = "Column::TagId",
		to = "super::tags::Column::Id",
		on_update = "NoAction",
		on_delete = "Cascade"
	)]
	Tags,
}

impl Related<super::bundles::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::Bundles.def()
	}
}

impl Related<super::collections::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::Collections.def()
	}
}

impl Related<super::cosmetic::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::Cosmetic.def()
	}
}

impl Related<super::cosmetic_group::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::CosmeticGroup.def()
	}
}

impl Related<super::discount::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::Discount.def()
	}
}

impl Related<super::tags::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::Tags.def()
	}
}

impl ActiveModelBehavior for ActiveModel {}
