//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.14

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "discount")]
pub struct Model {
	#[sea_orm(primary_key)]
	pub id: i32,
	#[sea_orm(column_type = "Text")]
	pub name: String,
	#[sea_orm(column_type = "Text", nullable)]
	pub description: Option<String>,
	#[sea_orm(column_type = "Text", nullable, unique)]
	pub code: Option<String>,
	pub percent_off: Option<i32>,
	pub amount_off_minor: Option<i64>,
	#[sea_orm(column_type = "Text", nullable)]
	pub currency: Option<String>,
	pub starts_at: Option<DateTimeWithTimeZone>,
	pub ends_at: Option<DateTimeWithTimeZone>,
	pub enabled: bool,
	pub applies_to_all: bool,
	pub min_subtotal_minor: Option<i64>,
	pub max_redemptions: Option<i32>,
	pub max_per_player: Option<i32>,
	pub redemptions: i32,
	#[sea_orm(column_type = "Text", nullable)]
	pub paynow_id: Option<String>,
	pub created_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
	#[sea_orm(has_many = "super::discount_redemption::Entity")]
	DiscountRedemption,
	#[sea_orm(has_many = "super::discount_target::Entity")]
	DiscountTarget,
}

impl Related<super::discount_redemption::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::DiscountRedemption.def()
	}
}

impl Related<super::discount_target::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::DiscountTarget.def()
	}
}

impl ActiveModelBehavior for ActiveModel {}
