//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.14

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "discount_redemption")]
pub struct Model {
	#[sea_orm(primary_key)]
	pub id: i64,
	pub discount_id: i32,
	pub player_id: i32,
	pub transaction_id: Option<i32>,
	pub redeemed_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
	#[sea_orm(
		belongs_to = "super::discount::Entity",
		from = "Column::DiscountId",
		to = "super::discount::Column::Id",
		on_update = "NoAction",
		on_delete = "Cascade"
	)]
	Discount,
	#[sea_orm(
		belongs_to = "super::transaction::Entity",
		from = "Column::TransactionId",
		to = "super::transaction::Column::Id",
		on_update = "NoAction",
		on_delete = "SetNull"
	)]
	Transaction,
	#[sea_orm(
		belongs_to = "super::user::Entity",
		from = "Column::PlayerId",
		to = "super::user::Column::Id",
		on_update = "NoAction",
		on_delete = "Cascade"
	)]
	User,
}

impl Related<super::discount::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::Discount.def()
	}
}

impl Related<super::transaction::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::Transaction.def()
	}
}

impl Related<super::user::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::User.def()
	}
}

impl ActiveModelBehavior for ActiveModel {}
