//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.14

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "emote")]
pub struct Model {
	#[sea_orm(primary_key)]
	pub id: i32,
	pub asset_id: Option<i32>,
	#[sea_orm(column_type = "Text")]
	pub name: String,
	pub created_at: DateTimeWithTimeZone,
	pub updated_at: DateTimeWithTimeZone,
	pub enabled: bool,
	#[sea_orm(column_type = "Text", nullable)]
	pub stripe_price_id: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
	#[sea_orm(
		belongs_to = "super::asset::Entity",
		from = "Column::AssetId",
		to = "super::asset::Column::Id",
		on_update = "NoAction",
		on_delete = "NoAction"
	)]
	Asset,
	#[sea_orm(has_many = "super::emote_package::Entity")]
	EmotePackage,
	#[sea_orm(has_many = "super::player_owned_emote::Entity")]
	PlayerOwnedEmote,
}

impl Related<super::asset::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::Asset.def()
	}
}

impl Related<super::emote_package::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::EmotePackage.def()
	}
}

impl Related<super::player_owned_emote::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::PlayerOwnedEmote.def()
	}
}

impl ActiveModelBehavior for ActiveModel {}
