//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.14

use super::sea_orm_active_enums::TransactionProvider;
use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "ownership_grant")]
pub struct Model {
	#[sea_orm(primary_key)]
	pub id: i64,
	pub player_id: i32,
	pub cosmetic_id: i32,
	pub provider: TransactionProvider,
	pub transaction_id: Option<i32>,
	pub transaction_line_id: Option<i64>,
	pub days: Option<i32>,
	pub granted_at: DateTimeWithTimeZone,
	pub active: bool,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
	#[sea_orm(
		belongs_to = "super::cosmetic::Entity",
		from = "Column::CosmeticId",
		to = "super::cosmetic::Column::Id",
		on_update = "NoAction",
		on_delete = "Cascade"
	)]
	Cosmetic,
	#[sea_orm(
		belongs_to = "super::transaction::Entity",
		from = "Column::TransactionId",
		to = "super::transaction::Column::Id",
		on_update = "NoAction",
		on_delete = "SetNull"
	)]
	Transaction,
	#[sea_orm(
		belongs_to = "super::transaction_line::Entity",
		from = "Column::TransactionLineId",
		to = "super::transaction_line::Column::Id",
		on_update = "NoAction",
		on_delete = "SetNull"
	)]
	TransactionLine,
	#[sea_orm(
		belongs_to = "super::user::Entity",
		from = "Column::PlayerId",
		to = "super::user::Column::Id",
		on_update = "NoAction",
		on_delete = "Cascade"
	)]
	User,
}

impl ActiveModelBehavior for ActiveModel {}
