//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.14

use super::sea_orm_active_enums::TransactionProvider;
use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "player_owned_cosmetic")]
pub struct Model {
	#[sea_orm(primary_key, auto_increment = false)]
	pub player_id: i32,
	#[sea_orm(primary_key, auto_increment = false)]
	pub cosmetic_id: i32,
	pub acquired_via: TransactionProvider,
	pub transaction_id: Option<i32>,
	pub acquired_at: DateTimeWithTimeZone,
	pub transaction_line_id: Option<i64>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
	#[sea_orm(
		belongs_to = "super::cosmetic::Entity",
		from = "Column::CosmeticId",
		to = "super::cosmetic::Column::Id",
		on_update = "NoAction",
		on_delete = "Cascade"
	)]
	Cosmetic,
	#[sea_orm(
		belongs_to = "super::transaction::Entity",
		from = "Column::TransactionId",
		to = "super::transaction::Column::Id",
		on_update = "NoAction",
		on_delete = "SetNull"
	)]
	Transaction,
	#[sea_orm(
		belongs_to = "super::transaction_line::Entity",
		from = "Column::TransactionLineId",
		to = "super::transaction_line::Column::Id",
		on_update = "NoAction",
		on_delete = "SetNull"
	)]
	TransactionLine,
	#[sea_orm(
		belongs_to = "super::user::Entity",
		from = "Column::PlayerId",
		to = "super::user::Column::Id",
		on_update = "NoAction",
		on_delete = "Cascade"
	)]
	User,
}

impl Related<super::cosmetic::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::Cosmetic.def()
	}
}

impl Related<super::transaction::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::Transaction.def()
	}
}

impl Related<super::transaction_line::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::TransactionLine.def()
	}
}

impl Related<super::user::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::User.def()
	}
}

impl ActiveModelBehavior for ActiveModel {}
