//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.14

use super::sea_orm_active_enums::SessionEndReason;
use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "play_session")]
pub struct Model {
	#[sea_orm(primary_key)]
	pub id: i64,
	pub player_id: i32,
	pub started_at: DateTimeWithTimeZone,
	pub last_heartbeat_at: DateTimeWithTimeZone,
	pub ended_at: Option<DateTimeWithTimeZone>,
	pub end_reason: Option<SessionEndReason>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
	#[sea_orm(
		belongs_to = "super::user::Entity",
		from = "Column::PlayerId",
		to = "super::user::Column::Id",
		on_update = "NoAction",
		on_delete = "Cascade"
	)]
	User,
}

impl Related<super::user::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::User.def()
	}
}

impl ActiveModelBehavior for ActiveModel {}
