//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.14

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "player_client_info")]
pub struct Model {
	#[sea_orm(primary_key, auto_increment = false)]
	pub player_id: i32,
	#[sea_orm(column_type = "Text", nullable)]
	pub client_version: Option<String>,
	#[sea_orm(column_type = "Text", nullable)]
	pub minecraft_version: Option<String>,
	#[sea_orm(column_type = "Text", nullable)]
	pub loader: Option<String>,
	#[sea_orm(column_type = "Text", nullable)]
	pub os: Option<String>,
	#[sea_orm(column_type = "Text", nullable)]
	pub os_version: Option<String>,
	#[sea_orm(column_type = "Text", nullable)]
	pub java_version: Option<String>,
	pub first_seen_at: DateTimeWithTimeZone,
	pub last_seen_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
	#[sea_orm(
		belongs_to = "super::user::Entity",
		from = "Column::PlayerId",
		to = "super::user::Column::Id",
		on_update = "NoAction",
		on_delete = "Cascade"
	)]
	User,
}

impl Related<super::user::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::User.def()
	}
}

impl ActiveModelBehavior for ActiveModel {}
