//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.14

use super::sea_orm_active_enums::TransactionProvider;
use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "player_owned_emote")]
pub struct Model {
	#[sea_orm(primary_key, auto_increment = false)]
	pub player_id: i32,
	#[sea_orm(primary_key, auto_increment = false)]
	pub emote_id: i32,
	pub acquired_via: TransactionProvider,
	pub transaction_id: Option<i32>,
	pub acquired_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
	#[sea_orm(
		belongs_to = "super::emote::Entity",
		from = "Column::EmoteId",
		to = "super::emote::Column::Id",
		on_update = "NoAction",
		on_delete = "Cascade"
	)]
	Emote,
	#[sea_orm(
		belongs_to = "super::transaction::Entity",
		from = "Column::TransactionId",
		to = "super::transaction::Column::Id",
		on_update = "NoAction",
		on_delete = "SetNull"
	)]
	Transaction,
	#[sea_orm(
		belongs_to = "super::user::Entity",
		from = "Column::PlayerId",
		to = "super::user::Column::Id",
		on_update = "NoAction",
		on_delete = "Cascade"
	)]
	User,
}

impl Related<super::emote::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::Emote.def()
	}
}

impl Related<super::transaction::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::Transaction.def()
	}
}

impl Related<super::user::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::User.def()
	}
}

impl ActiveModelBehavior for ActiveModel {}
