//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.12



use sea_orm :: entity :: prelude :: * ;

# [derive (Clone , Debug , PartialEq , DeriveEntityModel , Eq)] # [sea_orm (table_name = "player")] pub struct Model { # [sea_orm (primary_key , auto_increment = false)] pub minecraft_uuid : Uuid , }

# [derive (Copy , Clone , Debug , EnumIter , DeriveRelation)] pub enum Relation { # [sea_orm (has_many = "super::player_cosmetic::Entity")] PlayerCosmetic , }

impl Related < super :: player_cosmetic :: Entity > for Entity { fn to () -> RelationDef { Relation :: PlayerCosmetic . def () } }

impl Related < super :: cosmetic :: Entity > for Entity { fn to () -> RelationDef { super :: player_cosmetic :: Relation :: Cosmetic . def () } fn via () -> Option < RelationDef > { Some (super :: player_cosmetic :: Relation :: Player . def () . rev ()) } }

impl ActiveModelBehavior for ActiveModel { }