//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.12

pub use super :: cosmetic :: Entity as Cosmetic ;
pub use super :: player :: Entity as Player ;
pub use super :: player_cosmetic :: Entity as PlayerCosmetic ;