//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.14

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "product_settings")]
pub struct Model {
	#[sea_orm(primary_key)]
	pub id: i32,
	#[sea_orm(unique)]
	pub cosmetic_id: Option<i32>,
	#[sea_orm(unique)]
	pub cosmetic_group_id: Option<i32>,
	#[sea_orm(unique)]
	pub bundle_id: Option<i32>,
	pub available_from: Option<DateTimeWithTimeZone>,
	pub available_until: Option<DateTimeWithTimeZone>,
	pub stock_limit: Option<i32>,
	pub customer_limit: Option<i32>,
	pub customer_limit_days: Option<i32>,
	pub gifting_disabled: bool,
	pub coupons_disabled: bool,
	pub requires_all: bool,
	pub expires_after_days: Option<i32>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
	#[sea_orm(
		belongs_to = "super::bundles::Entity",
		from = "Column::BundleId",
		to = "super::bundles::Column::Id",
		on_update = "NoAction",
		on_delete = "Cascade"
	)]
	Bundles,
	#[sea_orm(
		belongs_to = "super::cosmetic::Entity",
		from = "Column::CosmeticId",
		to = "super::cosmetic::Column::Id",
		on_update = "NoAction",
		on_delete = "Cascade"
	)]
	Cosmetic,
	#[sea_orm(
		belongs_to = "super::cosmetic_group::Entity",
		from = "Column::CosmeticGroupId",
		to = "super::cosmetic_group::Column::Id",
		on_update = "NoAction",
		on_delete = "Cascade"
	)]
	CosmeticGroup,
	#[sea_orm(has_many = "super::product_requirement::Entity")]
	ProductRequirement,
}

impl Related<super::bundles::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::Bundles.def()
	}
}

impl Related<super::cosmetic_group::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::CosmeticGroup.def()
	}
}

impl Related<super::product_requirement::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::ProductRequirement.def()
	}
}

impl ActiveModelBehavior for ActiveModel {}
