//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.14

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "product_requirement")]
pub struct Model {
	#[sea_orm(primary_key, auto_increment = false)]
	pub settings_id: i32,
	#[sea_orm(primary_key, auto_increment = false)]
	pub cosmetic_id: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
	#[sea_orm(
		belongs_to = "super::cosmetic::Entity",
		from = "Column::CosmeticId",
		to = "super::cosmetic::Column::Id",
		on_update = "NoAction",
		on_delete = "Cascade"
	)]
	Cosmetic,
	#[sea_orm(
		belongs_to = "super::product_settings::Entity",
		from = "Column::SettingsId",
		to = "super::product_settings::Column::Id",
		on_update = "NoAction",
		on_delete = "Cascade"
	)]
	ProductSettings,
}

impl Related<super::product_settings::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::ProductSettings.def()
	}
}

impl ActiveModelBehavior for ActiveModel {}
