//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.12

use sea_orm :: entity :: prelude :: * ;

# [derive (Debug , Clone , PartialEq , Eq , EnumIter , DeriveActiveEnum)] # [sea_orm (rs_type = "String" , db_type = "Enum" , enum_name = "cosmetic_type")] pub enum CosmeticType { # [sea_orm (string_value = "cape")] Cape , }