//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.14

use super::sea_orm_active_enums::TransactionStatus;
use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "transaction_line")]
pub struct Model {
	#[sea_orm(primary_key)]
	pub id: i64,
	pub transaction_id: i32,
	#[sea_orm(column_type = "Text", unique)]
	pub provider_line_id: String,
	#[sea_orm(column_type = "Text")]
	pub product_id: String,
	pub bundle_id: Option<i32>,
	pub cosmetic_group_id: Option<i32>,
	pub cosmetic_id: Option<i32>,
	pub recipient_id: Option<i32>,
	pub quantity: i32,
	pub price_minor: i64,
	pub discount_minor: i64,
	pub subtotal_minor: i64,
	pub tax_minor: i64,
	pub total_minor: i64,
	#[sea_orm(column_type = "Text")]
	pub currency: String,
	pub status: TransactionStatus,
	pub returned_minor: i64,
	pub returned_at: Option<DateTimeWithTimeZone>,
	pub created_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
	#[sea_orm(
		belongs_to = "super::bundles::Entity",
		from = "Column::BundleId",
		to = "super::bundles::Column::Id",
		on_update = "NoAction",
		on_delete = "SetNull"
	)]
	Bundles,
	#[sea_orm(
		belongs_to = "super::cosmetic::Entity",
		from = "Column::CosmeticId",
		to = "super::cosmetic::Column::Id",
		on_update = "NoAction",
		on_delete = "SetNull"
	)]
	Cosmetic,
	#[sea_orm(
		belongs_to = "super::cosmetic_group::Entity",
		from = "Column::CosmeticGroupId",
		to = "super::cosmetic_group::Column::Id",
		on_update = "NoAction",
		on_delete = "SetNull"
	)]
	CosmeticGroup,
	#[sea_orm(has_many = "super::cosmetic_ownership_event::Entity")]
	CosmeticOwnershipEvent,
	#[sea_orm(has_many = "super::player_owned_cosmetic::Entity")]
	PlayerOwnedCosmetic,
	#[sea_orm(
		belongs_to = "super::transaction::Entity",
		from = "Column::TransactionId",
		to = "super::transaction::Column::Id",
		on_update = "NoAction",
		on_delete = "Cascade"
	)]
	Transaction,
	#[sea_orm(
		belongs_to = "super::user::Entity",
		from = "Column::RecipientId",
		to = "super::user::Column::Id",
		on_update = "NoAction",
		on_delete = "SetNull"
	)]
	User,
}

impl Related<super::bundles::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::Bundles.def()
	}
}

impl Related<super::cosmetic::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::Cosmetic.def()
	}
}

impl Related<super::cosmetic_group::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::CosmeticGroup.def()
	}
}

impl Related<super::cosmetic_ownership_event::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::CosmeticOwnershipEvent.def()
	}
}

impl Related<super::player_owned_cosmetic::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::PlayerOwnedCosmetic.def()
	}
}

impl Related<super::transaction::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::Transaction.def()
	}
}

impl Related<super::user::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::User.def()
	}
}

impl ActiveModelBehavior for ActiveModel {}
