//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.14

use super::sea_orm_active_enums::PlayerRole;
use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "user")]
pub struct Model {
	#[sea_orm(primary_key)]
	pub id: i32,
	#[sea_orm(unique)]
	pub minecraft_uuid: Uuid,
	pub created_at: DateTimeWithTimeZone,
	pub blacklisted: bool,
	pub role: PlayerRole,
	pub particle_color: Option<i32>,
	pub refund_count: i32,
	pub eos_product_user_id: Option<String>,
	pub username: Option<String>,
	pub chargeback_count: i32,
	#[sea_orm(column_type = "Text", nullable, unique)]
	pub paynow_customer_id: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
	#[sea_orm(has_many = "super::daily_playtime::Entity")]
	DailyPlaytime,
	#[sea_orm(has_many = "super::monthly_active_login::Entity")]
	MonthlyActiveLogin,
	#[sea_orm(has_many = "super::player_equipped_cosmetic::Entity")]
	PlayerEquippedCosmetic,
	#[sea_orm(has_many = "super::player_owned_cosmetic::Entity")]
	PlayerOwnedCosmetic,
	#[sea_orm(has_many = "super::transaction_line::Entity")]
	TransactionLine,
}

impl Related<super::daily_playtime::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::DailyPlaytime.def()
	}
}

impl Related<super::monthly_active_login::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::MonthlyActiveLogin.def()
	}
}

impl Related<super::player_equipped_cosmetic::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::PlayerEquippedCosmetic.def()
	}
}

impl Related<super::player_owned_cosmetic::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::PlayerOwnedCosmetic.def()
	}
}

impl Related<super::cosmetic::Entity> for Entity {
	fn to() -> RelationDef {
		super::player_equipped_cosmetic::Relation::Cosmetic.def()
	}
	fn via() -> Option<RelationDef> {
		Some(super::player_equipped_cosmetic::Relation::User.def().rev())
	}
}

impl ActiveModelBehavior for ActiveModel {}
