//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.12



use sea_orm :: entity :: prelude :: * ;

# [derive (Clone , Debug , PartialEq , DeriveEntityModel , Eq)] # [sea_orm (table_name = "user")] pub struct Model { # [sea_orm (primary_key , auto_increment = false)] pub id : Uuid , # [sea_orm (unique)] pub minecraft_uuid : Uuid , }

# [derive (Copy , Clone , Debug , EnumIter , DeriveRelation)] pub enum Relation { # [sea_orm (has_many = "super::user_cosmetic::Entity")] UserCosmetic , }

impl Related < super :: user_cosmetic :: Entity > for Entity { fn to () -> RelationDef { Relation :: UserCosmetic . def () } }

impl Related < super :: cosmetic :: Entity > for Entity { fn to () -> RelationDef { super :: user_cosmetic :: Relation :: Cosmetic . def () } fn via () -> Option < RelationDef > { Some (super :: user_cosmetic :: Relation :: User . def () . rev ()) } }

impl ActiveModelBehavior for ActiveModel { }